use_frameworks!

platform :ios, '12.4'

target 'swiftdi_Example' do
  pod 'swiftdi', :path => '../'

  target 'swiftdi_Tests' do
    inherit! :search_paths

    
  end
end

install! 'cocoapods', :warn_for_unused_master_specs_repo => false
