platform :ios, '13.0'

target 'Dependiject_Example' do
  use_frameworks!
  
  pod 'Dependiject', :path => '../'
end

target 'Dependiject_Tests' do
  use_frameworks!
  
  pod 'Dependiject', :path => '../'
  pod 'MockingbirdFramework', '~> 0.20'
end

install! 'cocoapods', :warn_for_unused_master_specs_repo => false
